name: Claude parallel + best pick

on:
  workflow_dispatch:

env:  # ← APIキーはリポジトリSecretから渡す
  CLAUDE_API_KEY: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix: { run_id: [1,2,3,4] }
    steps:
      - name: Ask Claude for menus
        id: ask
        uses: anthropics/claude-code-base-action@v1
        with:
          prompt: |
            夏の日向きのさっぱりしたカレーのメニューを考えて
          model: sonnet-4
      - name: Save reply
        run: echo "${{ steps.ask.outputs.completion }}" > result-${{ matrix.run_id }}.txt
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: result-${{ matrix.run_id }}.txt

  pick-best:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { name: results, path: menus }
      - name: Let Claude choose least-sweet
        id: choose
        uses: anthropics/claude-code-base-action@v1
        with:
          prompt: |
            以下のメニュー案から最も甘みが少ないものを1つ選び、その理由を簡潔に述べてください。

            <<MENUS>>
          files: menus/*.txt   # ← <<MENUS>> に自動インライン
          model: sonnet-4
      - run: echo "${{ steps.choose.outputs.completion }}"