name: Claude parallel + best pick

on:
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run_id:
          - 1
          - 2
          - 3
          - 4
    steps:
      - name: Ask Claude for menus
        id: ask
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            夏の日向きのさっぱりしたカレーのメニューを考えて
          model: claude-4-0-sonnet-20250219
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      - name: Save reply
        run: echo "${{ steps.ask.outputs.completion }}" > result-${{ matrix.run_id }}.txt
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: result-${{ matrix.run_id }}.txt

  pick-best:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: results
          path: menus
      - name: Build combined prompt file
        run: |
          echo "以下のメニュー案から、最も甘みが少ないものを1つ選び、その理由も簡潔に述べてください。\n" > prompt.txt
          cat menus/*.txt >> prompt.txt
      - name: Let Claude choose least-sweet
        id: choose
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: prompt.txt
          model: claude-4-0-sonnet-20250219
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      - name: Let Claude pick best
        env:
          ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: echo "${{ steps.choose.outputs.completion }}"