name: Run Claude 4 times and select best

on: [workflow_dispatch]

jobs:
  generate-menus:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run_id: [1, 2, 3, 4]
    steps:
      - name: Run Claude Prompt for Menu
        run: |
          claude -p "夏の日向きのさっぱりしたカレーのメニューを考えて" --model Sonnet 4 > result-${{ matrix.run_id }}.txt

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: result-${{ matrix.run_id }}.txt

  evaluate-menu:
    runs-on: ubuntu-latest
    needs: generate-menus
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: results
          path: all_results

      - name: Concatenate for evaluation
        run: |
          cat all_results/*.txt > all_menus.txt

      - name: Let Claude pick best
        run: |
          claude -p "以下のカレーメニュー案の中で、最も甘みが少ないと思われるものを1つ選び、理由も簡単に述べてください:\n\n$(cat all_menus.txt)" --model Sonnet 4