

name: Test Artifact Workflow

on:
  push:
    branches:
      - main

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create file
        run: |
          echo "This is a test file for artifact transfer." > artifact-test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: artifact-test.txt

  download-artifact:
    runs-on: ubuntu-latest
    needs: create-artifact
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test-artifact

      - name: Show file content
        run: cat artifact-test.txt